[project]
name = "crypto-portfolio-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ccxt>=4.4.72",
    "matplotlib>=3.10.1",
    "mcp[cli]>=1.6.0",
]
